/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //cmmSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  moneyQualitySidebar: [
		{
			type: 'doc',
			id: 'principles/intro', // document ID
			label: 'Getting started', // sidebar label
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'category',
			label: 'Digital Properties', // sidebar label
			collapsible: true,
			link: {
        type: "doc",
				id: 'principles/digital/intro', // document ID
			},
			items: [
				{
					type: 'category',
					label: 'Decentralized', // sidebar label
					link: {
						type: "doc",
						id: 'principles/digital/decentralization/intro', // document ID
					},
					items: [
						'principles/digital/decentralization/intro',
					]
				}, {
					type: 'category',
					label: 'Secure', // sidebar label
					link: {
						type: "doc",
						id: 'principles/digital/security/intro', // document ID
					},
					items: [
						{
							type: 'category',
							label: 'Design',
							items: [
								'principles/digital/security/design',
							],
						}, {
							type: 'category',
							label: 'Tests',
							items: [
								'principles/digital/security/unittests',
							],
						}, {
							type: 'category',
							label: 'Audits',
							items: [
								'principles/digital/security/auditors',
								'principles/digital/security/software',
							],
						}, {
							type: 'category',
							label: 'Backups',
							items: [
								'principles/digital/security/backups',
							],
						},
					]
				}, {
					type: 'category',
					label: 'Compliant', // sidebar label
					items: [
						{
							type: 'category',
							label: 'Compliance',
							items: [
								'principles/digital/compliance/KYC',
								'principles/digital/compliance/AML',
								'principles/digital/compliance/Taxes'
							],
						}, {
							type: 'doc',
							id: 'principles/digital/compliance/cryptolaw',
							label: 'Legal Framework',
						}, {
							type: 'category',
							label: 'Jurisdictions for Funding',
							items: [
								'principles/digital/compliance/funding/issuer',
								'principles/digital/compliance/funding/HQ',
								'principles/digital/compliance/funding/investors',
							],
						}, {
							type: 'category',
							label: 'Jurisdictions for Negotiation',
							items: [
								'principles/digital/compliance/negotiation/issuer',
							],
						}, {
							type: 'category',
							label: 'Jurisdictions for Distribution',
							items: [
								'principles/digital/compliance/distribution/consumer',
							],
						}, 
					]
				}, 
			]
    }, 
	],

  valueChainSidebar: [
		{
			type: 'doc',
			id: 'intro', // document ID
			label: 'Getting started', // sidebar label
		}, {
			type: 'doc',
			id: 'bibliography', // document ID
			label: 'Bibliography', // sidebar label
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'category',
			label: 'Tokenization', // sidebar label
			link: {
        type: "doc",
				id: 'tokenization/intro', // document ID
			},
			collapsible: false,
			items: [
				{
					type: 'category',
					label: 'Tokenization Process',
					items: [
						'tokenization/process/tokens/index',
						'tokenization/process/tokenization-demand/index',
						'tokenization/process/tokenization-supply/index',
						'tokenization/process/tokenization-monetary-policy/index',
					],
				}, {
					type: 'category',
					label: 'Tokenization Models',
					items: [
						'tokenization/models/asset/index',
						'tokenization/models/asset-unbacked/index',
						'tokenization/models/asset-utility/index',
						'tokenization/models/asset-security/index',
						'tokenization/models/asset-stablecoins/index',
						'tokenization/models/asset-uoa/index',
						'tokenization/models/asset-nft/index',
					],
				}, {
					type: 'category',
					label: 'Tokenization Utilities',
					items: [
						'tokenization/utilities/utility/index',
						'tokenization/utilities/utility-id/index',
						'tokenization/utilities/utility-investment/index',
						'tokenization/utilities/utility-currency/index',
					],
				}, 
			],
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'category',
			label: 'Funding', // sidebar label
			link: {
        type: "doc",
				id: 'funding/intro', // document ID
			},
			collapsible: false,
			items: [{
					type: 'category',
					label: 'Preparing Funding',
					link: {
						type: "doc",
						id: 'funding/preparing/intro', // document ID
					},
					items: [{
							type: 'category',
							label: 'Perform Compliance',
							items: [
								'principles/digital/compliance/funding/issuer',
								'principles/digital/compliance/funding/HQ',
								'principles/digital/compliance/funding/investors',
							],
						}, {
							type: 'category',
							label: 'Advertise your Project',
							items: [
								'funding/advertising/watchers',
								'funding/advertising/press',
							],
						}, {
							type: 'category',
							label: 'Pitching Investors',
							items: [
								'funding/pitching/incubators',
								'funding/pitching/investors',
							],
						}, {
							type: 'category',
							label: 'Existing Launchpads',
							items: [
								'funding/launchpads',
							],
						}, 
					],
				}
			]
    }, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, 
  ],

  suiteSidebar: [
		{
			type: 'doc',
			id: 'suite/intro', // document ID
			label: 'Getting started', // sidebar label
		}, {
      type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'category',
			label: 'Tokenization Platform', // sidebar label
			link: {
        type: "doc",
				id: 'suite/dapp-admin/intro', // document ID
			},
			collapsible: false,
			items: [
				{
					type: 'category',
					label: 'Creating Cryptocommodity',
					items: [
						'suite/dapp-admin/create-token/description',
						{
							type: 'category',
							label: 'Designing your Token',
							link: {
								type: "doc",
								id: 'suite/dapp-admin/create-token/configure', // document ID
							},
							items: [
								'suite/dapp-admin/create-token/supplycurrent',
							],
						},
						'suite/dapp-admin/create-token/create-suite',
					],
				}, {
					type: 'category',
					label: 'Funding your Project',
					link: {
						type: "doc",
						id: 'suite/dapp-admin/funding-round/intro', // document ID
					},
					items: [
						'suite/dapp-admin/funding-round/prepare-funding-round',
						'suite/dapp-admin/funding-round/create-funding-round',
						'suite/dapp-admin/funding-round/manage-funding-round',
						'suite/dapp-admin/funding-round/close-funding-round',
					],
				}, {
					type: 'category',
					label: 'Deploying to Exchanges',
					items: [
						'suite/dapp-admin/exchanges/exchanges-deploy-choose',
						'suite/dapp-admin/exchanges/exchanges-deploy-dex',
						'suite/dapp-admin/exchanges/exchanges-deploy-cex',
					],
				}, {
					type: 'category',
					label: 'Managing Liquidity',
					items: [
						'suite/dapp-admin/liquidity/moving',
					],
				}, {
					type: 'category',
					label: 'Distributing Rewards',
					items: [
						'suite/dapp-admin/rewards/distributing-rewards',
					],
				}, {
					type: 'category',
					label: 'Admin DApp Structure',
					items: [
						'suite/dapp-admin/structure',
					],
				}, 
			]
    }, 	{
      type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'category',
			label: 'Tokens', // sidebar label
			collapsible: false,
			items: [
				{
					type: 'category',
					label: 'ICO Token',
					items: [
						'suite/token-ico/features',
						{
							type: 'category',
							label: 'Functionalities',
							items: [
								'suite/token-ico/token-ico-functionalities/structure',
								'suite/token-ico/token-ico-functionalities/invest',
								'suite/token-ico/token-ico-functionalities/price',
								'suite/token-ico/token-ico-functionalities/refund',
								'suite/token-ico/token-ico-functionalities/claim',
								'suite/token-ico/token-ico-functionalities/withdraw',
							],
						},
						'suite/token-ico/supported-standards',
						'suite/token-ico/compliant-jurisdictions',
						'suite/token-ico/reporting',
					],
				},  {
					type: 'category',
					label: 'Vesting Token',
					items: [
						'suite/token-vesting/features',
						'suite/token-vesting/create-token',
						'suite/token-vesting/deliver-token',
						'suite/token-vesting/reporting',
					],
				}, {
					type: 'category',
					label: 'Catallactic Token',
					items: [
						'suite/token-trading/features',
						{
							type: 'category',
							label: 'Functionalities',
							items: [
								'suite/token-trading/token-trading-functionalities/metadata',
								'suite/token-trading/token-trading-functionalities/supply',
								'suite/token-trading/token-trading-functionalities/transfer',
								'suite/token-trading/token-trading-functionalities/erc-20',
								'suite/token-trading/token-trading-functionalities/liquidity',
								'suite/token-trading/token-trading-functionalities/governance',
							],
						},
						'suite/token-trading/supported-standards',
						'suite/token-trading/compliant-jurisdictions',
						'suite/token-trading/reporting',
					],
				},
			]
		},
	],

  ecosystemSidebar: [
		{
			type: 'doc',
			id: 'ecosystem/ecosystem', // document ID
			label: 'Getting started', // sidebar label
		}, {
      type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'category',
			label: 'Infrastructure', // sidebar label
			link: {
        type: "doc",
				id: 'ecosystem/dlts/intro', // document ID
			},
			collapsible: false,
			items: [
				{
					type: 'category',
					label: 'Interoperability', // sidebar label
					link: {
						type: "doc",
						id: 'ecosystem/dlts/interop/intro', // document ID
					},
					items: [
						'ecosystem/dlts/interop/tools',
						'ecosystem/dlts/interop/patterns',
						'ecosystem/dlts/interop/services',
						'ecosystem/dlts/interop/ecosystem',
					]
				}, 
			]
		}
	]

};

module.exports = sidebars;
