/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //cmmSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tokenizationSidebar: [
		{
			type: 'doc',
			id: 'tokenization/intro', // document ID
			label: 'Getting started', // sidebar label
		}, {
      type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'html',
      value: '<span class="sidebar-heading w-100 text-center">Fundamentals</span>',
    }, {
      type: 'category',
      label: 'Principles',
      items: [
				{
					type: 'category',
					label: 'Decentralization',
					items: [
						'tokenization/decentralization/infra',
						'tokenization/decentralization/governance'
					],
				}, {
					type: 'category',
					label: 'Privacy',
					items: [
						'tokenization/privacy/privacy',
					],
				}, {
					type: 'category',
					label: 'Security',
					items: [
						'tokenization/security/security',
					],
				}, {
					type: 'category',
					label: 'Compliance',
					items: [
						'tokenization/compliance/KYC',
						'tokenization/compliance/AML',
						'tokenization/compliance/Taxes'
					],
				}, 
			],
    }, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'html',
      value: '<span class="sidebar-heading w-100 text-center">Tokenization</span>',
    }, {
      type: 'category',
      label: 'Commodities',
      items: [
				'tokenization/tokenomics/commodities',
			],
		}, {
      type: 'category',
      label: 'Value Engineering',
      items: [
				'tokenization/value/ecosystem',
				'tokenization/value/utility',
				'tokenization/value/value',
			],
    }, {
      type: 'category',
      label: 'Value Capture',
      items: [
				'tokenization/tokenomics/supply',

			],
    }, {
      type: 'category',
      label: 'Maturity Model',
      items: [
				'tokenization/value/cmm'
			],
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'html',
      value: '<span class="sidebar-heading w-100 text-center">Project Funding</span>',
    }, {
      type: 'category',
      label: 'Funding Rounds',
      items: [
				'tokenization/tokenomics/rounds',
				'tokenization/tokenomics/selling',
				'tokenization/tokenomics/taxes',
			],
		},  {
      type: 'category',
      label: 'Launchpads',
      items: [
				'tokenization/tokenomics/launchpads',
			],
		},  {
      type: 'category',
      label: 'TGE',
      items: [
				'tokenization/tokenomics/TGE',
			],
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'html',
      value: '<span class="sidebar-heading w-100 text-center">Token Negotiation</span>',
    }, {
      type: 'category',
      label: 'Planning Deployment',
      items: [
				'tokenization/tokenomics/planning',
			],
		}, {
      type: 'category',
      label: 'Deployment',
      items: [
				'tokenization/tokenomics/deployment',
			],
		}, {
      type: 'category',
      label: 'Trading',
      items: [
				'tokenization/tokenomics/trading',
			],
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'html',
      value: '<span class="sidebar-heading w-100 text-center">Token Operations</span>',
    }, {
			type: 'category',
      label: 'Distribution',
      items: [
				'tokenization/tokenomics/distribution',
			], 
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'html',
      value: '<span class="sidebar-heading w-100 text-center">Tokenomics</span>',
    }, {
			type: 'doc',
      label: 'Token Allocations',
			id: 'tokenization/tokenomics/allocations', // document ID
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'html',
      value: '<span class="sidebar-heading w-100 text-center">Monetary Policy</span>',
    }, {
      type: 'category',
      label: 'Monetary Policy',
      items: [
				'tokenization/tokenomics/monetary',
				'tokenization/tokenomics/stability',
			],
		}, 
  ],

  suiteSidebar: [
		{
			type: 'doc',
			id: 'suite/intro', // document ID
			label: 'Getting started', // sidebar label
		}, {
      type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'html',
      value: '<span class="sidebar-heading w-100 text-center">Admin DApp</span>',
    }, {
			type: 'category',
      label: 'Creating your Suite',
      items: [
				'suite/dapp-admin/create-suite',
			],
		}, {
			type: 'category',
      label: 'Funding your Project',
      items: [
				'suite/dapp-admin/create-funding-round',
				'suite/dapp-admin/plan-vesting',
			],
		}, {
			type: 'category',
      label: 'Deploying to Exchanges',
      items: [
				'suite/dapp-admin/exchanges-deploy-choose',
				'suite/dapp-admin/exchanges-deploy-dex',
				'suite/dapp-admin/exchanges-deploy-cex',
			],
		}, {
			type: 'category',
      label: 'Managing Liquidity',
      items: [
				'suite/dapp-admin/liquidity-unmanaged',
				'suite/dapp-admin/liquidity-capture-price',
				'suite/dapp-admin/liquidity-capture-value',
			],
		}, {
			type: 'category',
      label: 'Admin DApp Structure',
      items: [
				'suite/dapp-admin/structure',
			],
		}, {
      type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'html',
      value: '<span class="sidebar-heading">User DApps</span>',
    }, {
			type: 'category',
      label: 'ICO Purchase Widget',
      items: [
				'suite/dapp-catallactic-purchase/create-token',
				'suite/dapp-catallactic-purchase/deliver-token',
			],
		}, {
      type: 'category',
      label: 'ICO Status Tracker',
      items: [
				'suite/dapp-catallactic-status/create-token',
				'suite/dapp-catallactic-status/deliver-token',
			],
		}, {
      type: 'category',
      label: 'ICO Claim',
      items: [
				'suite/dapp-catallactic-claim/create-token',
				'suite/dapp-catallactic-claim/deliver-token',
			],
		}, {
      type: 'category',
      label: 'ICO Vesting Tracker',
      items: [
				'suite/dapp-catallactic-vesting/create-token',
				'suite/dapp-catallactic-vesting/deliver-token',
			],
		}, 	{
      type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
			type: 'html',
      value: '<span class="sidebar-heading">Tokens</span>',
    }, {
			type: 'category',
      label: 'ICO Token',
      items: [
				'suite/token-ico/features',
				{
					type: 'category',
					label: 'Functionalities',
					items: [
						'suite/token-ico/token-ico-functionalities/structure',
						'suite/token-ico/token-ico-functionalities/invest',
						'suite/token-ico/token-ico-functionalities/price',
						'suite/token-ico/token-ico-functionalities/refund',
						'suite/token-ico/token-ico-functionalities/claim',
						'suite/token-ico/token-ico-functionalities/withdraw',
					],
				},
				'suite/token-ico/supported-standards',
				'suite/token-ico/compliant-jurisdictions',
				'suite/token-ico/reporting',
			],
    },  {
      type: 'category',
      label: 'Vesting Token',
      items: [
				'suite/token-vesting/features',
				'suite/token-vesting/create-token',
				'suite/token-vesting/deliver-token',
				'suite/token-vesting/reporting',
			],
    }, {
      type: 'category',
      label: 'Catallactic Token',
      items: [
				'suite/token-trading/features',
				{
					type: 'category',
					label: 'Functionalities',
					items: [
						'suite/token-trading/token-trading-functionalities/metadata',
						'suite/token-trading/token-trading-functionalities/supply',
						'suite/token-trading/token-trading-functionalities/transfer',
						'suite/token-trading/token-trading-functionalities/erc-20',
						'suite/token-trading/token-trading-functionalities/liquidity',
						'suite/token-trading/token-trading-functionalities/governance',
					],
				},
				'suite/token-trading/supported-standards',
				'suite/token-trading/compliant-jurisdictions',
				'suite/token-trading/reporting',
			],
		},  {
      type: 'category',
      label: 'Escrow Token',
      items: [
				'suite/token-escrow/features',
				'suite/token-escrow/create-token',
				'suite/token-escrow/deliver-token',
				'suite/token-escrow/reporting',
			],
		},  {
      type: 'category',
      label: 'Security',
      items: [
				'suite/security/design',
				'suite/security/unittests',
				'suite/security/backups',
				'suite/security/audit',
			],
		},
	],

  defiSidebar: [
		{
			type: 'doc',
			id: 'defi/intro', // document ID
			label: 'Getting started', // sidebar label
		}, {
      type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
      type: 'html',
      value: '<span class="sidebar-heading w-100 text-center">DeFi Services</span>',
    }, {
      type: 'category',
      label: 'DeFi Services',
      items: ['defi/intro'],
    }, {
      type: 'category',
      label: 'Launchpad',
      items: ['defi/launchpad/launchpad'],
    }, {
      type: 'category',
      label: 'Payments',
      items: ['defi/payments/payments'],
    }, {
      type: 'category',
      label: 'Cards',
      items: ['defi/cards/cards'],
    }, {
      type: 'category',
      label: 'Lending',
      items: ['defi/lending/lending'],
    },
  ],



};

module.exports = sidebars;
